usefull_dict ={
  "Keywords": [
    "SELECT",
    "FROM",
    "WHERE",
    "GROUP BY",
    "HAVING",
    "ORDER BY",
    "JOIN",
    "INNER JOIN",
    "LEFT JOIN",
    "LEFT OUTER JOIN",
    "RIGHT JOIN",
    "RIGHT OUTER JOIN",
    "FULL JOIN",
    "UNION",
    "DISTINCT",
    "AS",
    "COUNT",
    "SUM",
    "AVG",
    "MIN",
    "MAX",
    "BETWEEN",
    "LIKE",
    "IN",
    "IS NULL",
    "IS NOT NULL",
    "LIMIT",
    "OFFSET",
    "ASCIICOMPARE",
    "COALESCE",
    "CASE",
    "CAST",
    "ON"
  ],
  "Multidim": [
    "ATTRIBUTE_NAME",
    "NOM_EXPLICIT",
    "DATA_TYPE",
    "IS_CALCULATED",
    "IS_MEASURE",
    "IS_DIMENSION",
    "EXPRESSION",
    "IS_VISIBLE",
    "GROUP",
    "CUBE_NAME",
    "CATALOG_NAME",
    "SOURCE"
  ],
  "Tabular": [
    "COLUMN_NAME",
    "NOM_EXPLICIT",
    "DATA_TYPE",
    "IS_CALCULATED",
    "IS_MEASURE",
    "EXPRESSION",
    "IS_VISIBLE",
    "TABLE_NAME",
    "CUBE_NAME",
    "CATALOG_NAME",
    "SOURCE"
  ],
  "Select_Dict": [
    "ALIAS_NAME",
    "COLUMN_NAME_OR_EXPRESSION",
    "TABLE_NAME",
    "TABLE_DESTINATION"
  ]
}